language: cpp

sudo: required
dist: trusty

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

before_script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libeigen3-dev; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install eigen; fi
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
