language: cpp

sudo: required
dist: trusty

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

before_script:
    - cd ch2
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
