language: cpp

sudo: required
dist: trusty

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    global:
        - PYTHON_VERSION=3.6

git:
  submodules: true

before_script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -q && sudo apt-get install python-setuptools libglew-dev libeigen3-dev; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install glew eigen; fi
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
